version: '2'
services:

  # Image for TPM trusted third party (RAT repository)
  provider-ttpsim:      
    image: registry.netsec.aisec.fraunhofer.de/ids/ttpsim
    ports:
      - "31337:31337"
    networks:
      - ids-wide

networks:
  ids-wide:
    driver: bridge
