version: '3'
services:

  # The core platform, mounts docker control socket and route definition into the image
  consumer-core:
    image: fraunhoferaisec/trusted-connector-core:${EXAMPLE_TAG:-develop}
    tty: true
    stdin_open: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../deploy/allow-all-flows.pl:/root/deploy/allow-all-flows.pl
      - ../etc/settings.mapdb:/root/etc/settings.mapdb
      - ../etc/consumer-keystore.p12:/root/etc/keystore.p12
      - ../etc/truststore.p12:/root/etc/truststore.p12
      - ./example-idscp2-server.xml:/root/deploy/example-idscp2-server.xml
    # Enable this port mappings for debugging or UI access from localhost
    ports:
#      - "5005:5005"
      - "8080:8080"
#      - "8443:8443"
    networks:
      - ids-wide
    profiles:
      - server

  # The core platform, mounts docker control socket and route definition into the image
  provider-core:
    image: fraunhoferaisec/trusted-connector-core:${EXAMPLE_TAG:-develop}
    tty: true
    stdin_open: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../deploy/allow-all-flows.pl:/root/deploy/allow-all-flows.pl
      - ../etc/settings2.mapdb:/root/etc/settings.mapdb
      - ../etc/provider-keystore.p12:/root/etc/keystore.p12
      - ../etc/truststore.p12:/root/etc/truststore.p12
      - ./example-idscp2-client.xml:/root/deploy/example-idscp2-client.xml
    # Enable this port mappings for debugging or UI access from localhost
    ports:
#      - "5005:5005"
      - "8081:8080"
#      - "8443:8443"
    networks:
      - ids-wide
    profiles:
      - client

networks:
  ids-wide:
    driver: bridge
