# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

#####################
# Site configs
title: Connector Documentation 1.0
owner:
  name: Industrial Data Space
  link: http://www.industrialdataspace.org
  email: info@industrialdataspace.org
description: > # this means to ignore newlines until "baseurl:"
  Industrial Data Space
baseurl: "/material-doc" # the subpath of your site, e.g. /blog

# Specific social links, now we support following social account:
# github, twitter, weibo, google-plus, instagram, facebook, stack-overflow
# To support more social links, edit url in _data/socials.yml
# Remenber, always use a name that support by Font Awesome, to make sure the
# icon is shown.
socials:
  - name: github
    user: aisec

#####################
# Site styles
palette:
  primary: "#009688" # teal, lighten-1
  secondary: "#4db6ac" # teal lighten-2
  tertiary: "#b2dfdb" # teal lighten-3
  colored_text: "#26a69a" # teal lighten-4
  highlight: "#f50057" # red

#####################
# Build settings
collections:
  docs:
    output: true

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  #style: compressed
